source "https://rubygems.org"

gem 'cucumber', '~>3.2.0'
gem 'capybara'
gem 'report_builder'
gem 'cpf_faker'
gem 'cucumber_statistics'
gem 'faker'
gem 'rspec'
gem 'site_prism'
gem 'selenium-webdriver'
gem 'brazilian_documents'
gem 'cpf_cnpj'
gem 'parallel_tests'
gem 'nokogiri'
gem 'solargraph'
gem 'bundler'
gem 'pry'
gem 'ffi'
